version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tutor_for_everyone
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      DB_HOST: 'db'
      DB_USER: 'example'
      DB_PASSWORD: 'password'
      DB_NAME: 'tutor_for_everyone'
      SANDBOX_MODE: 'True'
    depends_on:
      - db
    volumes:
      - "./src:/app/src"
    ports:
      - "8000:80"
    command: ["poetry", "run", "python", "src/manage.py", "runserver", "0.0.0.0:80"]
